services:
  php:
    container_name: app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - proxy

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - proxy
    ports:
      - "8081:80"



volumes:
  db_data:

networks:
  proxy:
    external: true
