services:
  php:
    container_name: app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - proxy

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - proxy
#    ports:
#      - "8081:80"

#  mariadb:
#    image: mariadb:latest
#    container_name: mariadb
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: app
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    networks:
#      - app-network

#volumes:
#  db_data:

networks:
  proxy:
    external: true
